# Last two digits of port number are the MAJOR.MINOR of the data source
# Everything ahead of the last two digits are standard for the given service
#
# Network name is st-{service name}-{service MAJOR.MINOR}
version: '2'
services:
  nginxproxy:
# Enable nginx debug and increase output verbosity
#    command: [nginx-debug, '-g', 'daemon off;']
    image: jwilder/nginx-proxy
    container_name: sourcetoad_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy_increase.conf:/etc/nginx/proxy.conf
    networks:
     - st-internal
  postgres94:
    image: postgres:9.4
    container_name: sourcetoad_postgres94
    ports:
      - "5494:5432"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    networks:
      - st-internal
    command: "postgres
                -c logging_collector='on'
                -c log_directory='/var/log/postgresql'
                -c log_filename='%Y-%m-%d.log'
                -c log_line_prefix='%t %v '
                -c log_statement='all'"
  mariadb105:
    image: mariadb:10.5
    container_name: sourcetoad_mariadb105
    ports:
      - "33105:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mariadb_user
      - MYSQL_PASSWORD=mariadb_pass
    networks:
      - st-internal
  mariadb104:
    image: mariadb:10.4
    container_name: sourcetoad_mariadb104
    ports:
      - "33104:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mariadb_user
      - MYSQL_PASSWORD=mariadb_pass
    networks:
      - st-internal
  mariadb103:
    image: mariadb:10.3
    container_name: sourcetoad_mariadb103
    ports:
      - "33103:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mariadb_user
      - MYSQL_PASSWORD=mariadb_pass
    networks:
      - st-internal
  mariadb102:
    image: mariadb:10.2
    container_name: sourcetoad_mariadb102
    ports:
      - "33102:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mariadb_user
      - MYSQL_PASSWORD=mariadb_pass
    networks:
      - st-internal
  redis32:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    container_name: sourcetoad_redis32
    ports:
      - "6332:6379"
    networks:
      - st-internal
networks:
    st-internal:
        external:
            name: st-internal
